name: Create Release

on:
  workflow_dispatch:
    inputs:
      version_type:
        type: choice
        description: Semantic Version Type
        options:
          - automatic
          - patch
          - minor
          - major

      pre_release:
        type: choice
        description: Stage
        options:
          - stable
          - rc
          - beta
          - alpha

jobs:
  release-it:
    runs-on: ubuntu-latest
    steps:
      - uses: tibdex/github-app-token@v2
        id: generate-token
        with:
          app_id: ${{ secrets.RELEASE_BOT_APP_ID }}
          private_key: ${{ secrets.RELEASE_BOT_APP_PRIVATE_KEY }}

      - name: checkout
        uses: actions/checkout@v3
        with:
          token: ${{ steps.generate-token.outputs.token }}
          # we need everything so release-it can compare the current version with the latest tag
          fetch-depth: 0

      - name: initialize mandatory git config
        run: |
          git config user.name "GitHub Release Bot"
          git config user.email release-bot@neolution.ch

      - name: install @release-it/keep-a-changelog
        run: yarn add release-it @release-it/keep-a-changelog @neolution-ch/release-it-dotnet-plugin

      - name: run release-it
        run: |
          params=()

          if [[ ${{ github.event.inputs.version_type }} != "automatic" ]]; then
              params+=(${{ github.event.inputs.version_type }})
          fi

          if [[ ${{ github.event.inputs.pre_release }} != "stable" ]]; then
              params+=(--preRelease=${{ github.event.inputs.pre_release }})
              params+=(--plugins.@release-it/keep-a-changelog.keepUnreleased)
              params+=(--no-plugins.@release-it/keep-a-changelog.strictLatest)
          fi

          params+=(--ci)
          params+=(--plugins.@neolution-ch/release-it-dotnet-plugin.nugetApiKey=${{ secrets.NUGET_API_KEY_NEOLUTION }})

          echo "command: release-it ${params[@]}"
          yarn release-it "${params[@]}"
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
